default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'mysql2' %>
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: db
  port: 3306
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: my_test_docker_project_development

test:
  <<: *default
  database: my_test_docker_project_test
  reconnect: true

production:
  <<: *default
  reconnect: true
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV['WEB_THREADS'] || ENV['SIDEKIQ_THREADS'] || 7 %>
  timeout: 3000
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_ADDR'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
